### ISSUE TITLE
Logging Note is a Zombie

### ISSUE THREAD

**Issue by conreid-838** [czottmann/obsidian-log-to-note#8] opened 2023-12-20 17:35 UTC
Uninstalling this plug-in leaves files behind that continue to force a logging note to be created repeatedly.

**Comment by czottmann** [comment] 2023-12-22 14:36
Thanks for the report, @conreid-838. I'll look into it!

**Comment by czottmann** [comment] 2024-01-02 09:54
@conreid-838 I have a hard time reproducing the issue. Could you give me more details? On which platform does this happen? Do you use iCloud Sync?

**Comment by czottmann** [comment] 2024-03-24 14:51
Can't reproduce, no feedback from reporter in 2 months. Closing.

**Closed as completed by czottmann** 2024-03-24 14:51 UTC
